version: '2'
services:
    homeletserver-app:
        image: homeletserver
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://homeletserver-postgresql:5432/homeletserver
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    homeletserver-postgresql:
        extends:
            file: postgresql.yml
            service: homeletserver-postgresql
